version: "3"
services:

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pokemon
      - POSTGRES_DB=secure_poke_api
      - POSTGRES_HOST_AUTH_METHOD=trust
